name: Run CI check on push

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  run_ci:
    name: Run CI
    uses: tbricks/itiviti-cpp-analyzer/.github/workflows/build_and_test.yml@main
    with:
      build_type: 'Debug'
      branch: ${{ github.ref_name }}
